export interface OfferLetterData {
    tenantName: string;
    agentName: string;
    propertyAddress: string;
    annualRent: number;
    agencyFees: number;
    totalPackage: number;
    date: string;
}

export const generateOfferLetter = (data: OfferLetterData) => {
    return `
    PROVISIONAL TENANCY OFFER & ACCEPTANCE
    Generated by MyEasyAgent - The Trusted Housing Partner

    1. THE PARTIES:
       Tenant: ${data.tenantName}
       Agent/Landlord Representative: ${data.agentName}

    2. THE PROPERTY:
       Address: ${data.propertyAddress}

    3. THE FINANCIALS:
       Annual Rent: ₦${data.annualRent.toLocaleString()}
       Agency/Legal Fees: ₦${data.agencyFees.toLocaleString()}
       TOTAL PACKAGE: ₦${data.totalPackage.toLocaleString()}

    4. THE AGREEMENT:
       The Tenant hereby makes a firm offer to lease the above property. 
       The Agent acknowledges receipt of this offer and agrees to reserve 
       the property for the Tenant for 48 Hours while the final 
       Tenancy Agreement is prepared.

    5. DISCLAIMER:
       This document is a Confirmation of Commercial Terms only. 
       It is NOT a Tenancy Agreement. Possession of the property is 
       subject to the signing of the final Lease Agreement between 
       the Landlord and Tenant.

    Verification Code: MEA-${Math.random().toString(36).substring(7).toUpperCase()}
    Generated on: ${data.date}
  `;
};

export const RED_FLAG_CHECKLIST = [
    {
        id: 'quit_notice',
        title: 'Quit Notice Trap',
        warning: 'The contract mentions waiving your right to a 6-month notice.',
        clause: 'Seek clarification on notice periods.'
    },
    {
        id: 'repair',
        title: 'Structural Repair Trap',
        warning: 'The tenant is listed as responsible for structural repairs (roof, walls).',
        clause: 'Structural repairs are standardly the Landlord\'s responsibility.'
    },
    {
        id: 'refund',
        title: 'Non-Refundable Deposit Trap',
        warning: 'Landlord keeps 10% if they change their mind.',
        clause: 'Deposits should be 100% refundable if the Landlord cancels.'
    }
];
